### PR TITLE
Wrote Node.js and Go sections

### PR DESCRIPTION
**Pull request by gg2001**

### CODE REVIEW

**Comment by shannona** [comment]
Wow! Terrific wow, I wasn't expecting to see this!

I have one suggestion for improving this prior to the merge. You frequently give the code and tell people the results, which are two of the crucial elements in a doc of this sort. But it's also helpful to break out the pieces and tell people what they do. In this case, it'd be great to talk about the most important functions that you use.

So, the first time you use the RPC call, say what it is, and if there are any tricks that people need to know about it. (Maybe they aren't.) And, the first time you access a block and access the wallet, show where you're doing that, what the command is, and how it's used.

We don't need to be repetitive, and we don't need to detail things as they become more obvious, but this is very helpful, especially in the earlier parts.

**Comment by gg2001** [comment]
I've revised the documents and added better explanations and mentions the quirks associated with the rpc libraries. I also added a section about generating Bitcoin addresses.

**Comment by shannona** [comment]
Thanks very much for the revisions. I think you got the balance just right: it looks terrific.

I'm merging; please let me know how you prefer to be credited in the README.

**Comment by gg2001** [comment]
For credits I think: `[gg2001](https://github.com/gg2001) (Go, Node.js sections)` would be fine.

**Comment by shannona** [comment]
Thanks, got it.

**Pull request merged**
