### PR TITLE
Chapter 07 Translated by @koreacomk reviewed by @namcios

### PR DESCRIPTION
**Pull request by KoreaComK**
Chapter 07 Translated by @KoreaComK revision needed

### CODE REVIEW

**Comment by namcios** [comment]
@shannona review finalized. PR ready for merge from my end.

**Comment by KoreaComK** [comment]
@shannona ready to merge. :)

**Comment by shannona** [comment]
Great, thank you.

**Comment by shannona** [comment]
Changed the base to merge this into portuguese-translation

**Comment by namcios** [comment]
> Changed the base to merge this into portuguese-translation

Thanks, hadn't spotted that.

**Pull request merged**
