### PR TITLE
translation of chapter 05_1 complete, pending review

### PR DESCRIPTION
**Pull request by icculp**
Finished, awaiting review

### CODE REVIEW

**Review by javiervargas — COMMENTED** [review]
* In Spanish there are two ways of treating the reader, one more formal and another closer addressing as Tú.    Line 7 starts address formally and line 9 address as Tu.  We should use the same way all text.
* Text "ese ya no es el case" should be "ese ya no es el caso".
* Text "pueden vencer de mempools" should be "también pueden vencer de la mempool"

**Review by javiervargas — APPROVED** [review]
Ok

**Comment by shannona** [comment]
So I see Javier has officially approved a number of this. Is that my mark that they're ready to be merged? Or are they still in process? Thanks!

**Comment by javiervargas** [comment]
Due we have some links to correct,  We're thinking about if merge now with a TODO note,  or make a full list with all names and links and update all chapters with that information.

**Comment by shannona** [comment]
Just let me know what you prefer. Happy to merge whenever you're ready.

**Comment by shannona** [comment]
Starting merges of all PRs with approved reviews.

**Pull request merged**
