### PR TITLE
Update 12_0_Using_Tor.md

### PR DESCRIPTION
**Pull request by javiervargas**

### CODE REVIEW

**Comment by ChristopherA** [comment]
Less comment on this particular PR, but part of what our ultimate objective with this chapter should teach. Why is it important for Bitcoin users to use Tor? What does it help protect a Bitcoin use against? What are the weaknesses or limitations of Tor when used with Bitcoin? Probably need to say a little about Tor and Lightning at some point.

**Comment by javiervargas** [comment]
> Less comment on this particular PR, but part of what our ultimate objective with this chapter should teach. Why is it important for Bitcoin users to use Tor? What does it help protect a Bitcoin use against? What are the weaknesses or limitations of Tor when used with Bitcoin? Probably need to say a little about Tor and Lightning at some point.

You're right,  I was assuming that the reader knew the details of tor.    I've added some lines more.    
Put in my to-do list add tor-related lightning content.

**Comment by shannona** [comment]
Lightning is the *next* chapter, so we can't include that here (yet). But do keep it in your thoughts for if we want to put something as an interlude in one of the Lightning chapters (when we get there).

**Comment by shannona** [comment]
And generally, thanks. Those look like good expansions.

**Pull request merged**
